# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-09 10:58
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0004_auto_20180309_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiver',
            name='phone',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(regex=b'^\\+?1?\\d{9,15}$')]),
        ),
    ]
