# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-10 13:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0006_auto_20180309_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiver',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
